### PR TITLE
Support npm@3 using native Node module lookup

### PR DESCRIPTION
**Pull request by smrq**
Similar to the PR by @unional, but this uses Node's built-in `require.resolve` function to perform the lookup, which guarantees that it will be found based on Node's lookup rules.  This works with both npm@2 and npm@3.

### CODE REVIEW

**Comment by unional** [comment]
@smrq, great idea.  But it didn't work on me.  casperjs is not running under Node, so `require.resolve` is undefined.

**Comment by smrq** [comment]
Huh, it Works On My Machine™.  I wonder if it has to do with how I'm spawning Casper.

**Comment by unional** [comment]
Are you using SpookyJS or something similar that runs casperjs under Node environment?

I run it directly through command line: `casperjs test blah`

**Comment by unional** [comment]
```
casperjs test .\vr\demo
PS E:\username\project> Test file: E:/username/project/vr/demo/testsuite.js
# Coffee machine visual tests
FAIL TypeError: 'undefined' is not a function (evaluating 'require.resolve( 'resemblejs/resemble.js' )'
```

**Comment by smrq** [comment]
No, although I am running through Node at some level, I'm using child_process.spawn to spawn a new Phantom process:

```
var phantomProcess = child.spawn(phantomBinaryPath, [runnerPath, JSON.stringify(casperOptions)]);
```

**Comment by smrq** [comment]
No, although I am running through Node at some level I'm using `child_process.spawn` to spawn a new Phantom process:

```
var phantomProcess = child.spawn(phantomBinaryPath, [runnerPath, JSON.stringify(casperOptions)]);
```

The runner at `runnerPath` itself spawns Casper like:

```
var casper = require('casper').create({ /* options */ });
var phantomcss = require(args.phantomCssPath + sep + 'phantomcss.js');
phantomcss.init({ /* options */ });
```

Which is a bit unusual, but I don't see how it would make `require.resolve` become magically defined.  What version of Casper are you using?  (I'm on 1.1.0-beta3)

**Comment by unional** [comment]
Same 1.1.0-beta3

**Comment by unional** [comment]
Which version of phantomjs are you using? I'm using `1.9.8`.

**Comment by smrq** [comment]
Oh, that could be relevant -- I'm using `1.9.17` from npm.  Maybe it's the version difference, maybe it has something to do with installing it from npm?

**Comment by unional** [comment]
Can you do `phantomjs -v` to see your version?  I tried with `1.9.18` from npm, but the code's version remains in `1.9.8`.

On the other hand, since this module support `1.9.7`, likely `require.resolve` is not available

**Comment by smrq** [comment]
Ah, didn't realize the versions weren't in sync.  It's `1.9.8` as well.

The mystery continues :ghost:

**Comment by unional** [comment]
Can you open your `phantomjs.js` file and search for `resolve` to see if you can find that function defined? Just checking.

**Comment by jamescryer** [comment]
I have accepted PR https://github.com/Huddle/PhantomCSS/pull/128

`require.resolve` didn't work for me - though I wish it did

**Pull request closed without merging**
