### PR TITLE
PhantomJS 2.0.x compability fix

### PR DESCRIPTION
**Pull request by lifeart**

### CODE REVIEW

**Comment by lifeart** [comment]
Tested on Phantoms: 1.9.8, 2.0.0, 2.0.1-developer

**Comment by jamescryer** [comment]
Thanks a lot for this.  Unfortunately it didn't work for me. On 1.9.8 with Windows 8 it throws an error when trying to open the temp file created in the decodeImage function. I believe this might be fixed by treating it as an asynchronous action, and waiting for the file to exist before trying to open it.

You can in fact just give Resemble.js the file paths of the two images, and skip the encode step; although this doesn't work for me with SlimerJS.

**Comment by lifeart** [comment]
Try to use it with absolute ```_currentDirectory``` value.
All filestystem functions in PahntomJS synchronous (

**Comment by etrust** [comment]
Hi James, I would like to invite you to be a part of a new project. How can I contact you to explain the details? Thanks Raphael

**Comment by jamescryer** [comment]
It works if I remove useage of `_currentDirectory` completely, I think this is because in the demo testsuite we're passing in absolute paths.

With the latest CasperJS/PhantomJS (testing on Windows 8) I'm seeing further problems with `pageManager` callback

`TypeError: undefined is not an object (evaluating 'img.width')`

I don't have the time to investigate more.

I need these changes to be backward compatible before I can accept the PR

**Comment by lifeart** [comment]
I think this is happens because temp HTML file not propertly loaded (paths?) have you trying to get ```body.innerHTML``` for debug? In code we have 
```var img = document.getElementsByTagName("img")[0];```
 and I think that 
```page.open(fileName, pageManager);```
 opens blank page.

In conclusion: phantom 1.9.8 over Win8 without ```_currentDirectory``` working?
and phantom 2.x.x over Win8 has ```TypeError: undefined is not an object (evaluating 'img.width')```?

I'm gonna trying to solve SlimerJS problems

**Comment by jamescryer** [comment]
Yes, though I haven't investigated fully.  As you say, perhaps all these are problems are related to path resolution in different environments.

My next available window to review is in two weeks, if you have the time it would be great to see these problems resolved before then.  Thanks again.

**Comment by Pszek** [comment]
Looks like CasperJS is adding compatibility: https://github.com/n1k0/casperjs/releases/tag/1.1-beta5

**Comment by booleanbetrayal** [comment]
I've been running CasperJS master with PhantomJS 2 support for a couple of weeks now. Everything working great. This PR can be closed, IMO.

**Comment by mknadler** [comment]
@booleanbetrayal I've been having some difficulty getting this stack set up properly. Can you tell me what exact versions of CasperJS and PhantomJS you're using?

**Comment by booleanbetrayal** [comment]
Hope this helps @mknadler ! --

```sh
$ casperjs --version
1.1.0-beta5
$ which casperjs
./node_modules/.bin/casperjs
$ phantomjs --version
2.1.1
$ which phantomjs
./node_modules/.bin/phantomjs
```

package.json
```js
{
...
    "devDependencies": {
        "browser-sync": "~2.11.1",
        "casperjs": "git://github.com/n1k0/casperjs.git",
        "phantomcss": "~0.11.1",
        "phantomjs-prebuilt": "~2.1.4",
            ...
    }
}

**Comment by mknadler** [comment]
@booleanbetrayal cheers! :tada:

**Comment by booleanbetrayal** [comment]
Would be a simple fix to PhantomCSS to point to the CasperJS beta, but not sure if the authors would want to do that yet. Seems stable enough to me though.

**Comment by jamescryer** [comment]
@booleanbetrayal is indeed correct. It works with the HEAD of CasperJS's Master branch, Very exciting!

Unfortunately the demo test suite doesn't work out of the box without using an http server to serve the demo page. This seems like a minor regression to me and unlikely to cause considerable problems in the wild.

I want to do some due diligence with regard to the upgrade path with [PhantomFlow](https://github.com/Huddle/PhantomFlow) and some simple internal test suites.  If that goes well I'll create a v0.x.x branch and bump to V1 in master referencing the latest dependencies.

**Comment by jamescryer** [comment]
I've bumped master branch to v1 which uses the latest CasperJS.  It's not ideal to be tracking master, but I think the benefit outweighs the risk. Upgrade went smoothly for me.

**Comment by booleanbetrayal** [comment]
:+1:

**Pull request closed without merging**
